/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#d8e2ff',
        'primary-container': '#00163a',
        'primary': '#adc6ff',
        'tertiary-fixed': '#6ffbbe',
        'on-primary': '#002e6a',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed-variant': '#004395',
        'tertiary-container': '#001c10',
        'surface-container-high': '#222a3d',
        'on-secondary-fixed': '#131b2e',
        'tertiary': '#4edea3',
        'on-primary-fixed': '#001a42',
        'surface-bright': '#31394d',
        'on-secondary-container': '#adb4ce',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-tertiary-fixed': '#002113',
        'surface-container-lowest': '#060e20',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'surface-variant': '#2d3449',
        'inverse-on-surface': '#283044',
        'on-surface': '#dae2fd',
        'surface-dim': '#0b1326',
        'surface': '#0b1326',
        'on-surface-variant': '#c6c6cd',
        'primary-fixed-dim': '#adc6ff',
        'tertiary-fixed-dim': '#4edea3',
        'on-primary-container': '#357df1',
        'on-secondary': '#283044',
        'surface-container-low': '#131b2e',
        'on-tertiary': '#003824',
        'secondary': '#bec6e0',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-tint': '#adc6ff',
        'outline': '#909097',
        'inverse-primary': '#005ac2',
        'surface-container-highest': '#2d3449',
        'error': '#ffb4ab',
        'on-tertiary-container': '#009365',
        'secondary-container': '#3f465c',
        'surface-container': '#171f33',
        'inverse-surface': '#dae2fd',
        'background': '#0b1326',
        'on-background': '#dae2fd',
        'outline-variant': '#45464d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
